/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AutoComplete: typeof import('./src/components/AutoComplete/index.vue')['default']
    PositionWatcher: typeof import('./src/components/PositionWatcher/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    View: typeof import('./src/components/Fence/view/index.vue')['default']
  }
}
