// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMapControlBar: typeof import('./../src/components/AMap/ControlBar/index.vue')['default']
    AMapFitView: typeof import('./../src/components/AMap/FitView/index.vue')['default']
    AMapGeolocation: typeof import('./../src/components/AMap/Geolocation/index.vue')['default']
    AMapMap: typeof import('./../src/components/AMap/Map/index.vue')['default']
    AMapMapType: typeof import('./../src/components/AMap/MapType/index.vue')['default']
    AMapMarker: typeof import('./../src/components/AMap/Marker/index.vue')['default']
    AMapScale: typeof import('./../src/components/AMap/Scale/index.vue')['default']
    AMapSearch: typeof import('./../src/components/AMap/Search/index.vue')['default']
    AMapToolbar: typeof import('./../src/components/AMap/Toolbar/index.vue')['default']
    AMapVector: typeof import('./../src/components/AMap/Vector/index.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    FenceView: typeof import('./../src/components/Fence/view/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
